#!/usr/bin/env bash
# Generated by generate_helm.py — do not edit by hand.
# Installs cert-manager, dynatrace-operator, and DynaKube CR in dependency order.
#
# Usage:
#   ./install.sh [--dry-run] [--skip-cert-manager] [--skip-wait]
#                [--namespace NS] [--help]
set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ── Configurable defaults (override via env or CLI flags) ──────────────
DT_NAMESPACE="${DT_NAMESPACE:-dynatrace}"
DRY_RUN="${DRY_RUN:-false}"
SKIP_CERT_MANAGER="${SKIP_CERT_MANAGER:-false}"
SKIP_WAIT="${SKIP_WAIT:-false}"

# ── Argument parsing ───────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run)           DRY_RUN=true; shift ;;
    --skip-cert-manager) SKIP_CERT_MANAGER=true; shift ;;
    --skip-wait)         SKIP_WAIT=true; shift ;;
    --namespace)         DT_NAMESPACE="$2"; shift 2 ;;
    --help|-h)
      echo "Usage: $0 [--dry-run] [--skip-cert-manager] [--skip-wait] [--namespace NS]"
      exit 0 ;;
    *) echo "Unknown flag: $1" >&2; exit 1 ;;
  esac
done

DRY_RUN_FLAG=""
[[ "$DRY_RUN" == "true" ]] && DRY_RUN_FLAG="--dry-run"

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo "=========================================="
echo " Dynatrace Helm Install (staged)"
echo "=========================================="
echo " Namespace : $DT_NAMESPACE"
echo " Dry-run   : $DRY_RUN"
echo "=========================================="

# ── Step 1/3: cert-manager ─────────────────────────────────────────────
if [[ "$SKIP_CERT_MANAGER" == "false" ]]; then
  echo -e "${BLUE}[1/3]${NC} Installing cert-manager..."
  helm repo add jetstack https://charts.jetstack.io --force-update 2>/dev/null || true
  helm upgrade --install cert-manager jetstack/cert-manager \
    --namespace cert-manager --create-namespace \
    --version v1.14.5 \
    -f "$DIR/00-cert-manager-values.yaml" \
    $DRY_RUN_FLAG

  if [[ "$SKIP_WAIT" == "false" && "$DRY_RUN" == "false" ]]; then
    echo "  Waiting for cert-manager controller pod..."
    kubectl wait --for=condition=Ready pod \
      -l app.kubernetes.io/name=cert-manager \
      -n cert-manager --timeout=300s

    echo "  Waiting for cert-manager cainjector pod..."
    kubectl wait --for=condition=Ready pod \
      -l app.kubernetes.io/name=cainjector \
      -n cert-manager --timeout=300s

    echo "  Waiting for cert-manager webhook pod..."
    kubectl wait --for=condition=Ready pod \
      -l app.kubernetes.io/name=webhook \
      -n cert-manager --timeout=300s

    # Poll until the webhook Service has a live endpoint (max 120s).
    # This gate prevents the CA injection race that caused prior failures.
    echo "  Polling cert-manager-webhook endpoint (max 120s)..."
    DEADLINE=$(( $(date +%s) + 120 ))
    while true; do
      EP=$(kubectl get endpoints cert-manager-webhook \
             -n cert-manager \
             -o jsonpath='{.subsets[0].addresses[0].ip}' 2>/dev/null || true)
      if [[ -n "$EP" ]]; then
        echo -e "  ${GREEN}cert-manager-webhook endpoint ready: $EP${NC}"
        break
      fi
      if [[ $(date +%s) -ge $DEADLINE ]]; then
        echo -e "  ${YELLOW}ERROR: cert-manager-webhook endpoint not ready after 120s.${NC}" >&2
        exit 1
      fi
      sleep 5
    done
  fi
  echo -e "${GREEN}✓ cert-manager installed${NC}"
else
  echo -e "${YELLOW}[1/3] Skipping cert-manager (--skip-cert-manager)${NC}"
fi

# ── Step 2/3: dynatrace-operator ───────────────────────────────────────
echo -e "${BLUE}[2/3]${NC} Installing dynatrace-operator..."
helm repo add dynatrace \
  https://raw.githubusercontent.com/Dynatrace/dynatrace-operator/main/config/helm/repos/stable \
  --force-update 2>/dev/null || true
# csidriver: disabled (classicFullStack or no oneAgent mode)
helm upgrade --install dynatrace-operator dynatrace/dynatrace-operator \
  --namespace "$DT_NAMESPACE" --create-namespace \
  -f "$DIR/10-operator-values.yaml" \
  $DRY_RUN_FLAG

if [[ "$SKIP_WAIT" == "false" && "$DRY_RUN" == "false" ]]; then
  echo "  Waiting for dynatrace-operator pod..."
  kubectl wait --for=condition=Ready pod \
    -l app.kubernetes.io/name=dynatrace-operator \
    -n "$DT_NAMESPACE" --timeout=300s || true

  echo "  Waiting for dynatrace-webhook pod..."
  kubectl wait --for=condition=Ready pod \
    -l app.kubernetes.io/component=webhook \
    -n "$DT_NAMESPACE" --timeout=300s
fi
echo -e "${GREEN}✓ dynatrace-operator installed${NC}"

# ── Step 3/3: DynaKube CR ─────────────────────────────────────────────
# The DynaKube CR is applied via kubectl — it is not managed by Helm.
# This is intentional: the CR is authored in dynakube_OCI.yaml and
# extracted verbatim; there is no benefit to wrapping it in Helm.
echo -e "${BLUE}[3/3]${NC} Applying DynaKube CR..."
if [[ "$DRY_RUN" == "true" ]]; then
  kubectl diff -f "$DIR/20-dynakube-cr.yaml" || true
else
  kubectl apply -f "$DIR/20-dynakube-cr.yaml"
fi
echo -e "${GREEN}✓ DynaKube CR applied${NC}"

echo ""
echo "=========================================="
echo " Deployment Complete!"
echo "=========================================="
echo ""
echo "Check status:"
echo "  kubectl get pods -n cert-manager"
echo "  kubectl get pods -n $DT_NAMESPACE"
echo "  kubectl get dynakubes -n $DT_NAMESPACE"
echo ""
echo "View logs:"
echo "  kubectl logs -n $DT_NAMESPACE -l app.kubernetes.io/component=webhook"
echo ""
