#!/usr/bin/env bash
# Generated by generate_helm.py — do not edit by hand.
# Uninstalls all staged releases in reverse dependency order.
#
# Usage:
#   ./uninstall.sh [--purge-namespaces] [--namespace NS] [--help]
set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

DT_NAMESPACE="${DT_NAMESPACE:-dynatrace}"
PURGE_NS="${PURGE_NS:-false}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --purge-namespaces) PURGE_NS=true; shift ;;
    --namespace)        DT_NAMESPACE="$2"; shift 2 ;;
    --help|-h)
      echo "Usage: $0 [--purge-namespaces] [--namespace NS]"
      exit 0 ;;
    *) echo "Unknown flag: $1" >&2; exit 1 ;;
  esac
done

GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

echo "=========================================="
echo " Dynatrace Helm Uninstall (staged)"
echo "=========================================="

# Step 1/3: DynaKube CR — must be removed FIRST.
# The operator webhook validates CR deletions. If the webhook pod is
# removed first, the API server cannot reach the admission endpoint
# and the delete request will be blocked.
echo -e "${BLUE}[1/3]${NC} Deleting DynaKube CR..."
kubectl delete -f "$DIR/20-dynakube-cr.yaml" --ignore-not-found=true
echo -e "${GREEN}✓ DynaKube CR removed${NC}"

# Step 2/3: dynatrace-operator
echo -e "${BLUE}[2/3]${NC} Uninstalling dynatrace-operator..."
helm uninstall dynatrace-operator --namespace "$DT_NAMESPACE" --ignore-not-found 2>/dev/null || true
if [[ "$PURGE_NS" == "true" ]]; then
  kubectl delete namespace "$DT_NAMESPACE" --ignore-not-found=true
fi
echo -e "${GREEN}✓ dynatrace-operator removed${NC}"

# Step 3/3: cert-manager
echo -e "${BLUE}[3/3]${NC} Uninstalling cert-manager..."
helm uninstall cert-manager --namespace cert-manager --ignore-not-found 2>/dev/null || true
if [[ "$PURGE_NS" == "true" ]]; then
  kubectl delete namespace cert-manager --ignore-not-found=true
fi
echo -e "${GREEN}✓ cert-manager removed${NC}"

echo ""
echo "=========================================="
echo " Uninstall Complete!"
echo "=========================================="
echo ""
