# Source: dynatrace-operator/templates/Common/webhook/poddisruptionbudget-webhook.yaml
# v1 version supported since k8s 1.21
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: dynatrace-webhook
  namespace: dynatrace
  labels:
    app.kubernetes.io/name: dynatrace-operator
    app.kubernetes.io/version: "1.8.1"
    app.kubernetes.io/component: webhook
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: webhook

---
# Source: dynatrace-operator/templates/Common/operator/deployment-operator.yaml
# Copyright 2021 Dynatrace LLC

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynatrace-operator
  namespace: dynatrace
  annotations:
  labels:
    dynatrace.com/install-source: manifest
    app.kubernetes.io/name: dynatrace-operator
    app.kubernetes.io/version: "1.8.1"
    app.kubernetes.io/component: operator
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      name: dynatrace-operator
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        dynatrace.com/inject: "false"
      labels:
        app.kubernetes.io/name: dynatrace-operator
        app.kubernetes.io/version: "1.8.1"
        app.kubernetes.io/component: operator
        name: dynatrace-operator
    spec:
      containers:
        - name: operator
          args:
            - operator
          # Replace this with the built image name
          image: public.ecr.aws/dynatrace/dynatrace-operator:v1.8.1@sha256:aee68816f3d37d02df1f2afb5898153dbcb9b34274e2bf98b4429bdc77774c28
          imagePullPolicy: Always
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DT_OPERATOR_IMAGE
              value: public.ecr.aws/dynatrace/dynatrace-operator:v1.8.1@sha256:aee68816f3d37d02df1f2afb5898153dbcb9b34274e2bf98b4429bdc77774c28
            - name: DT_HOST_AVAILABILITY_DETECTION
              value: "true"
            - name: DT_CRD_STORAGE_MIGRATION
              value: "true"
            
            - name: modules.json
              value: |
                {
                  "csiDriver": false,
                  "activeGate": true,
                  "oneAgent": true,
                  "extensions": true,
                  "logMonitoring": true,
                  "edgeConnect": true,
                  "supportability": true,
                  "kubernetesMonitoring": true,
                  "kspm": true
                }
            
            - name: GOMEMLIMIT
              value: 116MiB
            
            - name: APP_VERSION
              value: "1.8.1"
          ports:
            - containerPort: 10080
              name: livez
            - containerPort: 8080
              name: metrics
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /livez
              port: livez
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
          startupProbe:
            exec:
              command:
              - /usr/local/bin/dynatrace-operator
              - startup-probe
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 1
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
            seccompProfile:
              type: RuntimeDefault
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
                      - ppc64le
                      - s390x
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
      serviceAccountName: dynatrace-operator
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      tolerations:
        - key: kubernetes.io/arch
          value: arm64
          effect: NoSchedule
        - key: kubernetes.io/arch
          value: amd64
          effect: NoSchedule
        - key: kubernetes.io/arch
          value: ppc64le
          effect: NoSchedule
        - key: kubernetes.io/arch
          value: s390x
          effect: NoSchedule

---
# Source: dynatrace-operator/templates/Common/webhook/deployment-webhook.yaml
# Copyright 2021 Dynatrace LLC

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynatrace-webhook
  namespace: dynatrace
  annotations:
  labels:
    app.kubernetes.io/name: dynatrace-operator
    app.kubernetes.io/version: "1.8.1"
    app.kubernetes.io/component: webhook
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      internal.dynatrace.com/component: webhook
      internal.dynatrace.com/app: webhook
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        dynatrace.com/inject: "false"
        kubectl.kubernetes.io/default-container: webhook
      labels:
        app.kubernetes.io/name: dynatrace-operator
        app.kubernetes.io/version: "1.8.1"
        app.kubernetes.io/component: webhook
        internal.dynatrace.com/component: webhook
        internal.dynatrace.com/app: webhook
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "topology.kubernetes.io/zone"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              internal.dynatrace.com/component: webhook
              internal.dynatrace.com/app: webhook
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: DoNotSchedule
          nodeTaintsPolicy: Honor
          labelSelector:
            matchLabels:
              internal.dynatrace.com/component: webhook
              internal.dynatrace.com/app: webhook
      volumes:
      - name: certs-dir
        secret:
          secretName: dynatrace-webhook-certs
          defaultMode: 420
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
                      - ppc64le
                      - s390x
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
      containers:
        - name: webhook
          args:
            - webhook-server
            # OLM mounts the certificates here, so we reuse it for simplicity
            - --certs-dir=/tmp/k8s-webhook-server/serving-certs/
          image: public.ecr.aws/dynatrace/dynatrace-operator:v1.8.1@sha256:aee68816f3d37d02df1f2afb5898153dbcb9b34274e2bf98b4429bdc77774c28
          imagePullPolicy: Always
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: WEBHOOK_PORT
              value: "8443"
            - name: HEALTH_PROBE_BIND_ADDRESS
              value: ":10080"
            - name: METRICS_BIND_ADDRESS
              value: ":8383"
            
            - name: GOMEMLIMIT
              value: 116MiB
            
            - name: modules.json
              value: |
                {
                  "csiDriver": false,
                  "activeGate": true,
                  "oneAgent": true,
                  "extensions": true,
                  "logMonitoring": true,
                  "edgeConnect": true,
                  "supportability": true,
                  "kubernetesMonitoring": true,
                  "kspm": true
                }
          readinessProbe:
            httpGet:
              path: /readyz
              port: livez
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /livez
              port: livez
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
          ports:
            - name: server-port
              containerPort: 8443
            - name: livez
              containerPort: 10080
            - name: metrics
              containerPort: 8383
          resources:
            requests:
              cpu: 300m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 128Mi
          volumeMounts:
            - name: certs-dir
              mountPath: /tmp/k8s-webhook-server/serving-certs/
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
            seccompProfile:
              type: RuntimeDefault
      serviceAccountName: dynatrace-webhook
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      tolerations:
        - key: kubernetes.io/arch
          value: arm64
          effect: NoSchedule
        - key: kubernetes.io/arch
          value: amd64
          effect: NoSchedule
        - key: kubernetes.io/arch
          value: ppc64le
          effect: NoSchedule
        - key: kubernetes.io/arch
          value: s390x
          effect: NoSchedule

---
# Source: dynatrace-operator/templates/Common/webhook/mutatingwebhookconfiguration.yaml
# Copyright 2021 Dynatrace LLC

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: dynatrace-webhook
  annotations:
    cert-manager.io/inject-ca-from: dynatrace/dynatrace-webhook
  labels:
    app.kubernetes.io/name: dynatrace-operator
    app.kubernetes.io/version: "1.8.1"
    app.kubernetes.io/component: webhook
webhooks:
  - name: webhook.pod.dynatrace.com
    reinvocationPolicy: IfNeeded
    failurePolicy: Ignore
    timeoutSeconds: 10
    rules:
      - apiGroups: [ "" ]
        apiVersions: [ "v1" ]
        operations: [ "CREATE" ]
        resources: [ "pods" ]
        scope: Namespaced
    namespaceSelector:
      matchExpressions:
        - key: dynakube.internal.dynatrace.com/instance
          operator: Exists
    clientConfig:
      service:
        name: dynatrace-webhook
        namespace: dynatrace
        path: /inject
    admissionReviewVersions: [ "v1" ]
    sideEffects: None
  - name: webhook.ns.dynatrace.com
    reinvocationPolicy: IfNeeded
    failurePolicy: Ignore
    timeoutSeconds: 10
    rules:
      - apiGroups: [ "" ]
        apiVersions: [ "v1" ]
        operations: [ "CREATE", "UPDATE"]
        resources: [ "namespaces" ]
        scope: Cluster
    clientConfig:
      service:
        name: dynatrace-webhook
        namespace: dynatrace
        path: /label-ns
    admissionReviewVersions: [ "v1" ]
    sideEffects: None

---
# Source: dynatrace-operator/templates/Common/webhook/validatingwebhookconfiguration.yaml
# Copyright 2021 Dynatrace LLC

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: dynatrace-webhook
  annotations:
    cert-manager.io/inject-ca-from: dynatrace/dynatrace-webhook
  labels:
    app.kubernetes.io/name: dynatrace-operator
    app.kubernetes.io/version: "1.8.1"
    app.kubernetes.io/component: webhook
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: dynatrace-webhook
        namespace: dynatrace
        path: /validate-dynatrace-com-v1beta3-dynakube
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - dynatrace.com
        apiVersions:
          - v1beta3
        resources:
          - dynakubes
    name: v1beta3.dynakube.webhook.dynatrace.com
    timeoutSeconds: 10
    sideEffects: None
    matchPolicy: Exact
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: dynatrace-webhook
        namespace: dynatrace
        path: /validate-dynatrace-com-v1beta4-dynakube
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - dynatrace.com
        apiVersions:
          - v1beta4
        resources:
          - dynakubes
    name: v1beta4.dynakube.webhook.dynatrace.com
    timeoutSeconds: 10
    sideEffects: None
    matchPolicy: Exact
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: dynatrace-webhook
        namespace: dynatrace
        path: /validate-dynatrace-com-v1beta5-dynakube
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - dynatrace.com
        apiVersions:
          - v1beta5
        resources:
          - dynakubes
    name: v1beta5.dynakube.webhook.dynatrace.com
    timeoutSeconds: 10
    sideEffects: None
    matchPolicy: Exact
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: dynatrace-webhook
        namespace: dynatrace
        path: /validate-dynatrace-com-v1beta6-dynakube
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - dynatrace.com
        apiVersions:
          - v1beta6
        resources:
          - dynakubes
    name: v1beta6.dynakube.webhook.dynatrace.com
    timeoutSeconds: 10
    sideEffects: None
    matchPolicy: Exact
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: dynatrace-webhook
        namespace: dynatrace
        path: /validate-dynatrace-com-v1alpha1-edgeconnect
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - dynatrace.com
        apiVersions:
          - v1alpha1
        resources:
          - edgeconnects
    name: v1alpha1.edgeconnect.webhook.dynatrace.com
    timeoutSeconds: 10
    sideEffects: None
    matchPolicy: Exact
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: dynatrace-webhook
        namespace: dynatrace
        path: /validate-dynatrace-com-v1alpha2-edgeconnect
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - dynatrace.com
        apiVersions:
          - v1alpha2
        resources:
          - edgeconnects
    name: v1alpha2.edgeconnect.webhook.dynatrace.com
    timeoutSeconds: 10
    sideEffects: None
    matchPolicy: Exact
